{"name": "test_Create_New_User", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'UserData.json'", "trace": "scope = 'module'\n\n    @pytest.fixture\n    def start_exec(scope=\"module\"):\n        global file # it will make file global - used everywhere\n>       file = open('UserData.json', 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: 'UserData.json'\n\nTestCases\\test_CreateUser.py:12: FileNotFoundError"}, "start": 1652782946471, "stop": 1652782946471, "uuid": "5d220b55-fd7a-4f55-8b0f-fd705c4cacf2", "historyId": "0282e1f10134c55817d93d01035e792d", "testCaseId": "17bebb43ada1cc26d66737d2524d5b48", "fullName": "TestCases.test_CreateUser#test_Create_New_User", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_CreateUser"}, {"name": "host", "value": "DESKTOP-DNTITBP"}, {"name": "thread", "value": "18392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_CreateUser"}]}